name = "ma-project"
main = "src/index.ts"
compatibility_date = "2023-04-18"
workers_dev = false
compatibility_flags = ["experimental:nodejs_compat_v2"]

[vars]
PGHOST = "ep-yellow-violet-a8iazcg7.eastus2.azure.neon.tech"
PGDATABASE = "mindarc-db"
PGUSER = "mindarc-db_owner"
PGPASSWORD = "Pwbyuh2l1IcG"
ENDPOINT_ID = "ep-yellow-violet-a8iazcg7"
API_KEY = "dekap4kkbtxwzt02qg6sr5e4cmj3btp08c6ufzdo0wd4m4aiqzscdf1n7o61t043"